version: '3.8'

services:
  app:
    image: quay.io/skylab/yildizplace-backend:1.0
    ports:
      - "443:443"
    depends_on:
      - db
      - redis
    command:
      [
        "-XX:MaxRAMPercentage=75.0",
        "-XX:+UseG1GC",
        "-XX:+UseStringDeduplication",
        "-XX:+ExitOnOutOfMemoryError",
        "-Xshare:on",
      ]
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: yildizplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server"]

volumes:
  pg-data:
